### ISSUE TITLE
Todo before next iteration

### ISSUE THREAD

**Issue by dagalufh** [dagalufh/TellstickNode#52]
- [x] Ensure that sensor configuration remains after reboot. Allow the sensor to **not** be seen for 10 saves, then remove the configuration.
- [ ] Create a site for device configuration. This is to set specific settings for each unique device. (Device name, autoremote on each action, ignore at resets)
- [ ] Create a watcher functionality for sensors. (For a specific sensor, select data type, if datatype equals a specific value, trigger an event)

More checkboxes will be added if needed.
